apiVersion: v1




kind: ReplicationController



metadata:
  name: webrc
  labels: 
    app: webapp


spec:
  replicas: 3
  selector:
    app: webapp
  template:
    metadata:
      name: webpod
      labels:
        app: webapp
    spec:
      containers:
         - name: webpp
           image: nginx
           ports:
             - containerPort: 80

