#apiVersion: v1
#kind: Service
#metadata:
  #  name: my-service
    #spec:
  # selector:
    # app.kubernetes.io/name: MyApp
      #  ports:
    #    - protocol: TCP
      #      port: 8000
        #      targetPort: 8080



apiVersion: v1
kind: Service
metadata:
  name: myservice  
  labels:
    app: myapp
spec:
  ports:
  - nodePort: 30500
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: myapp
  type: NodePort
